//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdpSensorRelayer.EmailWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailWebService.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/CreateEmailAndSend", ReplyAction="http://tempuri.org/IEmailService/CreateEmailAndSendResponse")]
        bool CreateEmailAndSend(string emailTo, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/CreateEmailAndSend", ReplyAction="http://tempuri.org/IEmailService/CreateEmailAndSendResponse")]
        System.Threading.Tasks.Task<bool> CreateEmailAndSendAsync(string emailTo, string subject, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : UdpSensorRelayer.EmailWebService.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<UdpSensorRelayer.EmailWebService.IEmailService>, UdpSensorRelayer.EmailWebService.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateEmailAndSend(string emailTo, string subject, string body) {
            return base.Channel.CreateEmailAndSend(emailTo, subject, body);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEmailAndSendAsync(string emailTo, string subject, string body) {
            return base.Channel.CreateEmailAndSendAsync(emailTo, subject, body);
        }
    }
}
